### ISSUE TITLE
could not resolved

### ISSUE THREAD

**Issue by Pppllll** [foxBMS/foxbms#9]
I based your documents(Setting an Eclipse Workspace),install it step by step。the last import the project and build it。NO binaries
the version 1.6.4    foxconda 3.03  
![微信图片_20201213011203](https://user-images.githubusercontent.com/75654915/101990345-6f724500-3ce1-11eb-91d6-029c2b6f9397.png)
![微信图片_20201213011340](https://user-images.githubusercontent.com/75654915/101990346-726d3580-3ce1-11eb-9bae-2b4735bf61a5.png)
![微信图片_20201213012147](https://user-images.githubusercontent.com/75654915/101990364-9b8dc600-3ce1-11eb-8550-56e6c96e8362.png)

**Comment by foxBMS** [comment]
Dear @Pppllll,

The binaries are built as the last message of the build system is a success message: ``'build_primry' finished successfully (...s)``.

The binary is found in ``build\primary\embedded-software\mcu-primary\src\general\``.

The errors you are seeing are from Eclipse about not finding some symbols. But the build system does not need a correct Eclipse setup as it uses the file system as information basis.

Of course a correct Eclipse setupos makes development much better, therefore 'd recommend to check that the include paths are correnctly set (These are the default and should work if you installted foxconda3 to the suggested directory):

![image](https://user-images.githubusercontent.com/24648128/102065856-5ceb2f00-3df9-11eb-9904-1993b6bda4bf.png)


Best regards,
The foxBMS Team

**Comment by Pppllll** [comment]
Dear the foxBMS Team
this is my include paths，just like you show me。but error&nbsp; remains。&nbsp; The way of foxconda3 is according to what you say。Build successful，but there is no Debug file ，i can not launch in debug and run model。&nbsp;


&nbsp;




By the Anaconda&nbsp; promote build&nbsp;python&nbsp;tools\waf&nbsp;-h also wrroy。







when buidl successfully，the erriors are remind，It's the same as before。and there is no Debug file ，i can not launch in debug and run model。&nbsp;This problem has been bothering me for a long time。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "foxBMS/foxbms"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 下午5:47
收件人:&nbsp;"foxBMS/foxbms"<foxbms@noreply.github.com&gt;;
抄送:&nbsp;"蛮"<182428293@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [foxBMS/foxbms] could not resolved (#9)





 
Dear @Pppllll,
 
The binaries are built as the last message of the build system is a success message: 'build_primry' finished successfully (...s).
 
The binary is found in build\primary\embedded-software\mcu-primary\src\general\.
 
The errors you are seeing are from Eclipse about not finding some symbols. But the build system does not need a correct Eclipse setup as it uses the file system as information basis.
 
Of course a correct Eclipse setupos makes development much better, therefore 'd recommend to check that the include paths are correnctly set (These are the default and should work if you installted foxconda3 to the suggested directory):
 

 
Best regards,
 The foxBMS Team

**Comment by foxBMS** [comment]
Dear @Pppllll,

your comment is not rendered correctly. Could please share again what does not work?

What do you mean by *i can not launch in debug and run model*? Are you unable to flash the hardware? What hardware are you using? Could you please share the output of ``build\primary\embedded-software\mcu-primary\src\general\`` after the build has finished?
You also try to restart the indexer of Eclipse as the screenshot shows.

![image](https://user-images.githubusercontent.com/24648128/102254675-3fa58600-3f09-11eb-8d46-8292ce1ff455.png)

But this is only related to Eclipse, not to the build.

If you have problems with Eclipse you could also try the VS Code workspace we provide since our latest release [v1.6.4](https://github.com/foxBMS/foxbms/releases/tag/v1.6.4). We provide an experimental VS Code setup, to overcome problem of a non functional Eclipse workspace. The VS Code setup is found [here](https://github.com/foxBMS/foxbms/tree/v1.6.4/tools/vscode). However this VS Code setup is experimental and should only be used in cases where setting up an Eclipse workspace fails.

Best regards,
The foxBMS Team

**Comment by Pppllll** [comment]
there is the build\primary\embedded-software\mcu-primary\src\general\ of output. I haven't connected the hardware yet.but I wrote a little project，when i click the run or debug button。the project will generate a debug file（a Binares&nbsp;in it）。i can place the breakpoint and&nbsp; run the progam。 but when i use your project，it tell&nbsp; me “launch&nbsp; fail. Binary not found” and there is no&nbsp;generate&nbsp;debug file。before you told me&nbsp;&nbsp;the build system does not need a correct Eclipse setup as it uses the file system as information basis。i want to sure the&nbsp;“launch&nbsp; fail. Binary not found”&nbsp;is it because of the previous problem（could not be resolved）or other reasaon.&nbsp;
I have used the second method, but it still hasn't been solved（index-&gt;rebuild）.This is my first time debugging embedded software through eclipse，&nbsp;Many fundamental issues are not very clear.thank you of you teach me.








------------------ 原始邮件 ------------------
发件人:                                                                                                                        "foxBMS/foxbms"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 凌晨2:12
收件人:&nbsp;"foxBMS/foxbms"<foxbms@noreply.github.com&gt;;
抄送:&nbsp;"蛮"<182428293@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [foxBMS/foxbms] could not resolved (#9)





 
Dear @Pppllll,
 
your comment is not rendered correctly. Could please share again what does not work?
 
What do you mean by i can not launch in debug and run model? Are you unable to flash the hardware? What hardware are you using? Could you please share the output of build\primary\embedded-software\mcu-primary\src\general\ after the build has finished?
 You also try to restart the indexer of Eclipse as the screenshot shows.
 

 
But this is only related to Eclipse, not to the build.
 
If you have problems with Eclipse you could also try the VS Code workspace we provide since our latest release v1.6.4. We provide an experimental VS Code setup, to overcome problem of a non functional Eclipse workspace. The VS Code setup is found here. However this VS Code setup is experimental and should only be used in cases where setting up an Eclipse workspace fails.
 
Best regards,
 The foxBMS Team

**Comment by foxBMS** [comment]
Dear @Pppllll,
 
Eclipse can not find any binary, because debugging in Eclipse is not supported.
 
Furthermore you need a foxBMS-hardware connected to the PC in order to flash the software on the device (we provide a tool for that, see [here](https://github.com/foxBMS/foxbms/tree/c5fb868b59468e59d5b47f56e72f46bb276e2a91/tools/flashtool)).
 
After that you need some kind of debugger (e.g., we have added an example for Jlink see [here](https://github.com/foxBMS/foxbms/tree/c5fb868b59468e59d5b47f56e72f46bb276e2a91/tools/ozone)) and debugger software (e.g., Ozone).
Based on that you can connect to the device and start debugging within the debugger software (**not** within Eclipse).
 
You can find more information on working with foxBMS in the online version of the documentation at [docs.foxbms.org](https://docs.foxbms.org) which provides a section on [how to get started](https://docs.foxbms.org/en/latest/getting_started/general/general.html).
 
Best regards,
The foxBMS Team

**Comment by Pppllll** [comment]
Dear the foxBMS Team：
&nbsp; &nbsp; &nbsp; &nbsp;I can run the project smoothly through JLINK .&nbsp;I&nbsp;establish a bootloader project。this bootloader project can&nbsp; guide my own APP(0x8040000)success. but your BMS can't guide(foxbms_primary_flash.bin).I would like to ask is the project need to do other processing.I've been confused for two weeks.I look forward to your reply.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "蛮"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 晚上8:24
***@***.***&gt;;

主题:&nbsp;回复： [foxBMS/foxbms] could not resolved (#9)



there is the build\primary\embedded-software\mcu-primary\src\general\ of output. I haven't connected the hardware yet.but I wrote a little project，when i click the run or debug button。the project will generate a debug file（a Binares in it）。i can place the breakpoint and&nbsp; run the progam。 but when i use your project，it tell&nbsp; me “launch&nbsp; fail. Binary not found” and there is no generate debug file。before you told me &nbsp;the build system does not need a correct Eclipse setup as it uses the file system as information basis。i want to sure the “launch&nbsp; fail. Binary not found” is it because of the previous problem（could not be resolved）or other reasaon. 
I have used the second method, but it still hasn't been solved（index-&gt;rebuild）.This is my first time debugging embedded software through eclipse， Many fundamental issues are not very clear.thank you of you teach me.








------------------ 原始邮件 ------------------
发件人:                                                                                                                        "foxBMS/foxbms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 凌晨2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [foxBMS/foxbms] could not resolved (#9)





 
Dear @Pppllll,
 
your comment is not rendered correctly. Could please share again what does not work?
 
What do you mean by i can not launch in debug and run model? Are you unable to flash the hardware? What hardware are you using? Could you please share the output of build\primary\embedded-software\mcu-primary\src\general\ after the build has finished?
 You also try to restart the indexer of Eclipse as the screenshot shows.
 

 
But this is only related to Eclipse, not to the build.
 
If you have problems with Eclipse you could also try the VS Code workspace we provide since our latest release v1.6.4. We provide an experimental VS Code setup, to overcome problem of a non functional Eclipse workspace. The VS Code setup is found here. However this VS Code setup is experimental and should only be used in cases where setting up an Eclipse workspace fails.
 
Best regards,
 The foxBMS Team

**Comment by foxBMS** [comment]
Dear @Pppllll,

Have you checked, that linker scripts of the bootloader application and foxBMS fit?

Best regards,
The foxBMS Team

**Comment by Pppllll** [comment]
Dear the foxBMS Team：
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;I CAN&nbsp;not&nbsp;transmit&nbsp; can Extended frame(eg.0x18FFB7F4).it can not pass the&nbsp;&nbsp; retHal = HAL_CAN_AddTxMessage(ptrHcan, &amp;can_txbuffer-&gt;buffer[can_txbuffer-&gt;ptrRead].msg, can_txbuffer-&gt;buffer[can_txbuffer-&gt;ptrRead].data, ptrMailbox);




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "蛮"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月4日(星期五) 凌晨0:09
***@***.***&gt;;

主题:&nbsp;回复： [foxBMS/foxbms] could not resolved (#9)



Dear the foxBMS Team：
&nbsp; &nbsp; &nbsp; &nbsp;I can run the project smoothly through JLINK . I&nbsp;establish a bootloader project。this bootloader project can&nbsp; guide my own APP(0x8040000)success. but your BMS can't guide(foxbms_primary_flash.bin).I would like to ask is the project need to do other processing.I've been confused for two weeks.I look forward to your reply.





------------------ 原始邮件 ------------------
发件人:                                                                                                                        "蛮"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 晚上8:24
***@***.***&gt;;

主题:&nbsp;回复： [foxBMS/foxbms] could not resolved (#9)



there is the build\primary\embedded-software\mcu-primary\src\general\ of output. I haven't connected the hardware yet.but I wrote a little project，when i click the run or debug button。the project will generate a debug file（a Binares in it）。i can place the breakpoint and&nbsp; run the progam。 but when i use your project，it tell&nbsp; me “launch&nbsp; fail. Binary not found” and there is no generate debug file。before you told me &nbsp;the build system does not need a correct Eclipse setup as it uses the file system as information basis。i want to sure the “launch&nbsp; fail. Binary not found” is it because of the previous problem（could not be resolved）or other reasaon. 
I have used the second method, but it still hasn't been solved（index-&gt;rebuild）.This is my first time debugging embedded software through eclipse， Many fundamental issues are not very clear.thank you of you teach me.








------------------ 原始邮件 ------------------
发件人:                                                                                                                        "foxBMS/foxbms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 凌晨2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [foxBMS/foxbms] could not resolved (#9)





 
Dear @Pppllll,
 
your comment is not rendered correctly. Could please share again what does not work?
 
What do you mean by i can not launch in debug and run model? Are you unable to flash the hardware? What hardware are you using? Could you please share the output of build\primary\embedded-software\mcu-primary\src\general\ after the build has finished?
 You also try to restart the indexer of Eclipse as the screenshot shows.
 

 
But this is only related to Eclipse, not to the build.
 
If you have problems with Eclipse you could also try the VS Code workspace we provide since our latest release v1.6.4. We provide an experimental VS Code setup, to overcome problem of a non functional Eclipse workspace. The VS Code setup is found here. However this VS Code setup is experimental and should only be used in cases where setting up an Eclipse workspace fails.
 
Best regards,
 The foxBMS Team
